%%% Muestra la tabla de comandos del sistema tutorial de octave
%
% Projecto kudos de octave 
% (C) 2013 Javier M. Mora-Merchan et al.
% BSD 3-Clause License


function ayuda
  newline=[char(10)];
  texto=[...
   '============================================================',newline,...
	 'Herramienta interactiva para aprender MATLAB/octave aplicado',newline,...
	 '============================================================',newline,...
	 newline,...
	 'COMANDOS DE AYUDA - Cómo optener ayuda',newline,...
	 '* "ayuda"            muestra la tabla de comandos disponibles',newline,...
	 newline,...
	 'COMANDOS DE INDICE - Listan los experimentos que cumplen ciertos criterios',newline,...
   '* "indice"           muestra el índice de todos los experimentos disponibles',newline,...
   '* "pista"            muestra el índice de los experimentos relacionados con el actual',newline,...
   '* "glosario"         muestra un listado de todos los términos definidos', newline,...
   '* "glosario ''term''"  muestra un índice de todos los experimentos relacionados con el término dado',newline,...
	 newline,...
   'COMANDOS DE MOVIMIENTO - Cambia de experimento sin verificar el actual',newline,...
	 '* "siguiente"        avanza al siguiente experimento',newline,...
	 '* "anterior"         retrocede al experimento anterior',newline,...
	 '* "irexperimento(N)" salta al experimento N',newline,...
	 newline,...
	 'COMANDOS PARA EXPERIMENTOS'
   '* "repite"           muestra nuevamente el experimento actual', ...
	                      ' (y reinicia las variables definidas en el experimento)',newline,...
	 '* "verificar"        determina si la tarea asignada se ha efectuado correctamente',...
	                      ' (en cuyo caso se avanzará a la siguiente tarea)',newline,...
	 newline,...
	 'La tecla TAB puede usarse para autocompletar estos comandos, funciones ', ...
	 'y variables previamente definidas',newline,...
	 newline,...
	 'Las teclas de cursor ARRIBA y ABAJO permiten recuperar comandos ', newline,...
	 'anteriormente escritos para ahorrar trabajo de copia. Una vez ', newline,...
	 'recuperado se pueden corregir, modificar o simplemente volverlos ', newline,...
	 'a ejecutar.'...
	 ];
  disp(texto);
end
